-- Seed data for Pakistan Tour Portal

-- Insert destinations
INSERT INTO destinations (name, location, category, rating, reviews_count, image_url, description, highlights, best_time, difficulty) VALUES
('Hunza Valley', 'Gilgit-Baltistan', 'Mountain', 4.9, 234, '/placeholder.svg?height=300&width=400', 'A breathtaking valley surrounded by towering peaks, ancient forts, and apricot orchards.', ARRAY['Baltit Fort', 'Attabad Lake', 'Rakaposhi View', 'Local Culture'], 'April - October', 'Moderate'),
('Lahore', 'Punjab', 'Cultural', 4.7, 456, '/placeholder.svg?height=300&width=400', 'The cultural heart of Pakistan with magnificent Mughal architecture and vibrant street life.', ARRAY['Badshahi Mosque', 'Lahore Fort', 'Food Street', 'Shalimar Gardens'], 'October - March', 'Easy'),
('Skardu', 'Gilgit-Baltistan', 'Adventure', 4.8, 189, '/placeholder.svg?height=300&width=400', 'Gateway to K2 and base camp for some of the world''s highest peaks.', ARRAY['K2 Base Camp', 'Shangrila Resort', 'Deosai Plains', 'Satpara Lake'], 'May - September', 'Challenging'),
('Karachi', 'Sindh', 'Urban', 4.5, 312, '/placeholder.svg?height=300&width=400', 'Pakistan''s largest city and economic hub with beautiful beaches and modern attractions.', ARRAY['Clifton Beach', 'Quaid''s Mausoleum', 'Port Grand', 'Empress Market'], 'November - February', 'Easy'),
('Swat Valley', 'Khyber Pakhtunkhwa', 'Nature', 4.6, 167, '/placeholder.svg?height=300&width=400', 'Known as the ''Switzerland of Pakistan'' for its lush green valleys and crystal-clear rivers.', ARRAY['Kalam Valley', 'Mahodand Lake', 'Ushu Forest', 'White Palace'], 'April - October', 'Moderate'),
('Islamabad', 'Capital Territory', 'Urban', 4.4, 298, '/placeholder.svg?height=300&width=400', 'The modern capital city nestled against the Margalla Hills with planned architecture.', ARRAY['Faisal Mosque', 'Margalla Hills', 'Pakistan Monument', 'Lok Virsa'], 'March - May, September - November', 'Easy');

-- Insert travel partners
INSERT INTO travel_partners (name, title, location, rating, reviews_count, experience, languages, specialties, avatar_url, description, price_range, verified, phone, email) VALUES
('Ahmad Khan', 'Mountain Guide & Trekking Expert', 'Hunza Valley', 4.9, 127, '8 years', ARRAY['English', 'Urdu', 'Burushaski'], ARRAY['Mountain Trekking', 'Cultural Tours', 'Photography'], '/placeholder.svg?height=100&width=100', 'Experienced mountain guide specializing in Karakoram range expeditions and cultural immersion tours.', '$50-80/day', TRUE, '+92 300 1234567', 'ahmad@example.com'),
('Fatima Ali', 'Cultural Heritage Specialist', 'Lahore', 4.8, 89, '6 years', ARRAY['English', 'Urdu', 'Punjabi'], ARRAY['Historical Tours', 'Food Tours', 'Art & Culture'], '/placeholder.svg?height=100&width=100', 'Passionate about sharing Pakistan''s rich cultural heritage through immersive historical and culinary experiences.', '$40-60/day', TRUE, '+92 300 2345678', 'fatima@example.com'),
('Rashid Ahmed', 'Adventure Sports Guide', 'Skardu', 4.9, 156, '10 years', ARRAY['English', 'Urdu', 'Balti'], ARRAY['Rock Climbing', 'Mountaineering', 'Base Camp Treks'], '/placeholder.svg?height=100&width=100', 'Professional mountaineer with extensive experience in K2 and other 8000m peak expeditions.', '$70-100/day', TRUE, '+92 300 3456789', 'rashid@example.com');

-- Insert hotels
INSERT INTO hotels (name, location, category, rating, reviews_count, price_range, image_url, description, amenities, features, phone, email) VALUES
('Hunza Serena Inn', 'Hunza Valley', 'Luxury', 4.8, 234, '$120-180', '/placeholder.svg?height=300&width=400', 'Luxury resort with stunning mountain views and traditional architecture.', ARRAY['Free WiFi', 'Restaurant', 'Spa', 'Mountain Views', 'Room Service'], ARRAY['24/7 Reception', 'Airport Shuttle', 'Laundry Service'], '+92 5813 457001', 'hunza@serena.com.pk'),
('Pearl Continental Lahore', 'Lahore', 'Luxury', 4.6, 456, '$90-140', '/placeholder.svg?height=300&width=400', 'Premier hotel in the heart of Lahore with modern amenities and excellent service.', ARRAY['Free WiFi', 'Pool', 'Gym', 'Multiple Restaurants', 'Business Center'], ARRAY['Valet Parking', 'Concierge', 'Conference Rooms'], '+92 42 111 505 505', 'pc.lahore@pchotels.com'),
('Shangrila Resort Skardu', 'Skardu', 'Resort', 4.7, 189, '$80-120', '/placeholder.svg?height=300&width=400', 'Beautiful lakeside resort known as ''Heaven on Earth'' with breathtaking scenery.', ARRAY['Lake Views', 'Restaurant', 'Boating', 'Garden', 'Room Service'], ARRAY['Lake Activities', 'Mountain Trekking', 'Cultural Tours'], '+92 5815 460523', 'info@shangrilaresorts.com');
